services:
  db:
    image: postgres:14-alpine
    container_name: amberos_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    container_name: amberos_api
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        NODE_ENV: development
    restart: always
    env_file:
      - .env
    ports:
      - "5001:5001"
    depends_on:
      - db

  web:
    container_name: amberos_web
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  postgres_data: