
FROM node:18-alpine AS base
WORKDIR /app
COPY backend/package.json backend/package-lock.json ./


FROM base AS development
RUN npm install
COPY backend/ .
CMD ["npm", "run", "dev"]


FROM base AS builder

RUN npm install

COPY backend/ .

RUN npm run build


FROM node:18-alpine AS production
WORKDIR /app

COPY --from=builder /app/package.json /app/package-lock.json ./

RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist
EXPOSE 5001

CMD ["node", "dist/index.js"]